### PR TITLE
New Authentication alerts using UIAlertController

### PR DESCRIPTION
**Pull request by koke**
I've ported `WPHTTPAuthenticationAlertView` to use `UIAlertController`
This should be right in theory but I haven't tested (or even run) this code yet

### CODE REVIEW

**Comment by SergioEstevao** [comment]
@koke do you want me to test this? I'm in the process of doing a bit of cleanup on this repo, and one of the things was to change this. It looks you already have the work done. 
What it the best way  to test? Change the password of site after login?

**Comment by koke** [comment]
For testing this, on a self hosted site with HTTP Auth enabled:

- Login from a fresh install. Make sure you get the auth dialog and it works.
- You should be able to use the app without any additional dialogs popping up
- Change the HTTP password. Refresh posts. You should get the auth dialog. Filling it should work
- Canceling the auth dialog doesn't show it again immediately and fails the request
- When the request is retried, the auth dialog is shown again

**Comment by SergioEstevao** [comment]
@koke I update some code and tested on a basic auth site. it's ready for your review.

**Comment by koke** [comment]
Some issues while testing. Not sure if regressions or existing bugs yet.

After enabling HTTP Auth on a blog already added to the app:
- If you go to the site details, two auth alerts pop up. When you cancel the top one, you get three more.
- If you go to posts and cancel the auth, there's a cryptic error: `The operation couldn't be completed. (NSURLErrorDomain error -1012.)`

On a fresh install:
- When you add the self hosted site, if you cancel the http auth alert it will crash.
- The app doesn't remember the credentials between launches. Which is even more annoying because every time you relaunch the app you get two alerts.

**Comment by SergioEstevao** [comment]
Can you test how it was before? Just to make sure if this is related to
these changes.

**Comment by koke** [comment]
On `develop`:

- When I launch the app, and on site details, the authentication alert pops up once. When I tap cancel it comes back about 4-5 times, but only one at a time.
- Canceling on sync posts shows the same error.
- It also forgets the password between launches.
- If I cancel on login, it also crashes.

**Comment by koke** [comment]
:shipit:

**Pull request merged**
